# Generated by Django 5.1.6 on 2025-02-16 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_artist', models.CharField(max_length=50)),
                ('description_artist', models.TextField()),
                ('contact_artist', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categorie', models.CharField(max_length=50)),
                ('description_categorie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_cart', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=30)),
                ('descrption_product', models.TextField()),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_product', models.SmallIntegerField()),
                ('state_product', models.CharField(max_length=50)),
                ('categorie_product', models.CharField(max_length=50)),
                ('artiste_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyArt_modele.categorie')),
                ('color_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyArt_modele.color')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_cartitem', models.SmallIntegerField(default=0)),
                ('cart_cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyArt_modele.cart')),
                ('product_cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyArt_modele.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_review', models.CharField(max_length=50)),
                ('email_review', models.CharField(max_length=50)),
                ('message_review', models.TextField()),
                ('rate_review', models.SmallIntegerField(default=0)),
                ('product_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyArt_modele.product')),
            ],
        ),
    ]
