# Generated by Django 5.1.6 on 2025-02-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyArt_modele', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate_product',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
