# Generated by Django 5.1.6 on 2025-02-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyArt_modele', '0003_product_reduction_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artiste_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyArt_modele.artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyArt_modele.categorie'),
        ),
    ]
