# Generated by Django 5.1.6 on 2025-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyArt_modele', '0005_alter_product_rate_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reduction_product',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
