# Generated by Django 5.1.6 on 2025-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyArt_modele', '0006_alter_product_reduction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='artworks/'),
        ),
    ]
