# Generated by Django 5.1.6 on 2025-04-08 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyArt_modele', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
